version: '3'

services:
    app1:
        image: nginx
        ports: 
            - "8090:80"
    app2:
        image: nginx
        environment:
            foo: $foo
        ports: 
            - "8096:80"
